name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    name: build
    steps:
      - uses: actions/checkout@v3

      - name: Check CMake version
        run: cmake --version

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Generate CMake project
        run: cmake -D CMAKE_BUILD_TYPE=Release -S. -Bbuild -G Ninja

      - name: Build 64bit release DLL
        run: cmake --build ./build --config Release --target GottvergessenLoader --

      - name: Check if Executable got built
        run: if (-Not (Test-Path -path "build/GottvergessenLoader.exe")) {throw 1}

      - name: Rename DLL to GottvergessenLoader-dev-{GITHUB_SHA}.exe
        run: |
          del GottvergessenLoader-dev-*.exe
          ren GottvergessenLoader.exe GottvergessenLoader-dev-${{github.sha}}.exe
        working-directory: build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: build/GottvergessenLoader-dev-*.exe
